services:
  database:
    image: mysql:5.6
    container_name: database
    restart: always
    networks:
      - wp-net
    volumes:
      - mysql-vol:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot@123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    networks: 
      - wp-net
    volumes:
      - wp-vol:/var/www/html/
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

networks:
  wp-net:

volumes: 
  mysql-vol:
  wp-vol:
